# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    # Temporary pre-allocation of sizes
    # Fruit - 
    # 
    {id: 0, size: 0.16, name: Fruit1},
    {id: 1, size: 0.16, name: Fruit2},
    {id: 2, size: 0.16, name: Fruit3},
    {id: 3, size: 0.16, name: Fruit4},
    {id: 4, size: 0.16, name: Fruit5},
    {id: 5, size: 0.16, name: Fruit6},
    {id: 6, size: 0.16, name: Fruit7},
    {id: 7, size: 0.16, name: Fruit8},
    {id: 8, size: 0.16, name: Fruit9},
    {id: 9, size: 0.16, name: Fruit10},
    {id: 10, size: 0.16, name: Fruit11},
    {id: 11, size: 0.16, name: Fruit12},
    {id: 12, size: 0.16, name: Weed1},
    {id: 13, size: 0.16, name: Weed2},
    {id: 14, size: 0.16, name: Weed3},
    {id: 15, size: 0.16, name: Weed4},
    {id: 50, size: 0.16, name: Uturn1},
    {id: 51, size: 0.16, name: Uturn2},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
